#List of words for use in Hangman game.
words = ["aardvark", 
         "baboon", 
         "camel", 
         "distracted", 
         "element", 
         "fiction",
         "gamble",
         "hesitate",
         "island",
         "joker",
         "laughing"
         "meditate",
         "neuron",
         "opulent",
         "programming",
         "quilt",
         "ridiculous",
         "simple",
         "traversal",
         "ubiquitous",
         "vulnerable",
         "welcome",
         "xray",
         "zebra"
]